// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://uvbespdkjqndcekyecsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YmVzcGRranFuZGNla3llY3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzg2OTEsImV4cCI6MjA2OTExNDY5MX0.Omb9HjH6tT1VdsI6rZtKHpHT7gEAs3LqG5ZQFCa-xEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
